version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        secretKey: 1234567890
    ports:
      - "3000:3000"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=3000
      - POSTGRES_URL=postgres://postgres:example@postgres:5432/cw_indonesia_platform
    restart: always
    container_name: cw-indonesia
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/cw-indonesia

  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cw_indonesia_platform
