locales: [en, id]
sections:
  - name: HOMEPAGE
    slug: intro
    order: 1
  - name: HOMEPAGE_province
    slug: province
    order: 2
  - name: HOMEPAGE_slide-one
    slug: slide-one
    order: 3
  - name: HOMEPAGE_slide-one-paging
    slug: slide-one-paging
    order: 4
  - name: HOMEPAGE_slide-one-button
    slug: slide-one-button
    order: 5
  - name: HOMEPAGE_slide-two
    slug: slide-two
    order: 6
  - name: HOMEPAGE_slide-two-paging
    slug: slide-two-paging
    order: 7
  - name: HOMEPAGE_slide-two-button
    slug: slide-two-button
    order: 8
  - name: HOMEPAGE_slide-three
    slug: slide-three
    order: 9
  - name: HOMEPAGE_slide-three-paging
    slug: slide-three-paging
    order: 10
  - name: HOMEPAGE_slide-three-button
    slug: slide-three-button
    order: 11
  - name: HOMEPAGE_slide-four
    slug: slide-four
    order: 12
  - name: HOMEPAGE_slide-four-paging
    slug: slide-four-paging
    order: 13
  - name: HOMEPAGE_slide-four-button
    slug: slide-four-button
    order: 14
  - name: HOMEPAGE_climate-watch
    slug: climate-watch-disclaimer
    order: 15
  - name: HOMEPAGE_climate-watch-button
    slug: climate-watch-button
    order: 16
  - name: HOMEPAGE_highlighted-stories
    slug: highlighted-stories
    order: 17
  - name: HOMEPAGE_highlighted-stories-button
    slug: highlighted-stories-button
    order: 18
  - name: NATIONAL_CONTEXT
    slug: national-context
    order: 19
  - name: NATIONAL_CONTEXT_socioeconomic-indicators
    slug: socioeconomic
    order: 20
  - name: NATIONAL_CONTEXT_socioeconomic-indicators_population
    slug: population
    order: 21
  - name: NATIONAL_CONTEXT_socioeconomic-indicators_economic-profile
    slug: economic
    order: 22
  - name: NATIONAL_CONTEXT_socioeconomic-indicators_energy
    slug: energy
    order: 23
  - name: NATIONAL_CONTEXT_socioeconomic-indicators_population-and-economic-profile-national-indicator-label
    slug: national-indicator-label
    order: 24
  - name: NATIONAL_CONTEXT_socioeconomic-indicators_population-and-economic-profile-province-indicator-label
    slug: province-indicator-label
    order: 25
  - name: NATIONAL_CONTEXT_socioeconomic-indicators_population-and-economic-profile-province-indicator-label
    slug: indicators-label
    order: 26
  - name: NATIONAL_CONTEXT_historical-emissions
    slug: historical-emissions
    order: 27
  - name: NATIONAL_CONTEXT_sectoral-activity
    slug: sectoral-activity
    order: 28
  - name: NATIONAL_CONTEXT_sectoral-activity-emissions
    slug: sectoral-activity-emissions
    order: 29
  - name: NATIONAL_CONTEXT_sectoral-activity-year-label
    slug: sectoral-activity-year-label
    order: 30
  - name: NATIONAL_CONTEXT_sectoral-activity-indicator-label
    slug: sectoral-activity-indicator-label
    order: 31
  - name: NATIONAL_CONTEXT_climate-funding
    slug: climate-funding
    order: 32
  - name: CLIMATE_GOALS
    slug: climate-goals
    order: 33
  - name: CLIMATE_GOALS_overview
    slug: overview
    order: 34
  - name: CLIMATE_GOALS_mitigation
    slug: mitigation
    order: 35
  - name: CLIMATE_GOALS_adaptation
    slug: adaptation
    order: 36
  - name: CLIMATE_GOALS_sectoral-information
    slug: sectoral-information
    order: 37