platforms:
  - name: indonesia_platform
    sections:
      - name: locations
        importer: Locations::ImportLocations
        datasets:
          - locations/locations
      - name: locations_members
        importer: Locations::ImportLocationMembers
        datasets:
          - locations/locations_groupings
      - name: historical_emissions
        importer: ImportHistoricalEmissions
        datasets:
          - historical_emissions/historical_emissions_metadata_sectors
          - historical_emissions/historical_emissions_data
      - name: emission_targets
        importer: ImportEmissionTargets
        datasets:
          - emission_targets
      - name: emission_activities
        importer: ImportEmissionActivities
        datasets:
          - emission_activities
      - name: commitment_timeline
        importer: ImportCommitmentTimelineEntries
        datasets:
          - commitment_timeline_entries
      - name: funding
        importer: ImportFundingOpportunities
        datasets:
          - opportunities
          - opportunities_id
      - name: indicators
        importer: ImportIndicators
        datasets:
          - indicators
          - indicators_id
          - socioeconomics
          - pc_forest
          - pc_energy
          - pc_agriculture
          - vulnerability_adaptivity
          - adaptation_included
      - name: metadata
        importer: ImportDataSources
        datasets:
          - data_sources
          - data_sources_id
      - name: province_plans
        importer: ImportProvincePlans
        datasets:
          - development_plans
          - development_plans_id
          - climate_plans
          - climate_plans_id
