apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: indonesia-platform
  namespace: climate-watch
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: indonesia-platform
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
