apiVersion: v1
kind: Service
metadata:
  namespace: climate-watch
  labels:
    name: indonesia-platform
  name: indonesia-platform
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: indonesia-platform
